Repository GTAIV-Complete-Edition-text/TLAD, pull requests merged in 2020-04, with the labels that each got.

#23 Add files via upload
  text/E1J1AUD.txt
Labels: help wanted

#24 初翻
  text/PBLB115.txt
Labels: bug, invalid

#28 Yutongbus2
  text/E1RAY1.txt
  text/E1S3AUD.txt
  text/EML11.txt
  text/EML12.txt
  text/EML13.txt
  text/JIMRACE.txt
  text/PBLB17.txt
  text/STUB3M1.txt
  text/STUB3M2.txt
  text/STUB3M4.txt
  text/STUB3M5.txt
  text/STUB3M7.txt
Labels: help wanted

#32 Yutongbus2
  text/HILOCRD.txt
Labels: 可以merge
